# Generated by Django 2.2.3 on 2019-12-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('content_type', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('teacher_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('search_type', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('query', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('location_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'information',
                'managed': False,
            },
        ),
    ]
